version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: fruit-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: fruitdb
      MYSQL_USER: fruituser
      MYSQL_PASSWORD: ""
    ports:
      - "3314:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: